<<<<<<< HEAD
permalink: /:day-:month-:year/:title/

exclude:              ["Gemfile", "Gemfile.lock"]

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge

paginate: 10
paginate_path: ":num"


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      styles : [highlight.css,post.css]
      scripts : [post.js]

title: Avis notes
description: "Thoughts, stories and ideas."
email: orlov.avis@yandex.ru
github_username: avis20

# undef
swiftype_searchId: "ncwR9a8S9CTx2q9SgsJm"
disqus_shortname: "rainyalley"

baseurl: /doc
url: "https://avis20.github.io"
#imgrepo: "http://127.0.0.1:4000/static/img"

=======
permalink: /:day-:month-:year/:title/

exclude:  ["Gemfile", "Gemfile.lock"]

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      styles : [post.css]
      scripts : [post.js]

title: Avis notes
description: "Thoughts, stories and ideas."
email: orlov.avis@yandex.ru
github_username: avis20

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge

baseurl: /doc
url: "https://avis20.github.io"
>>>>>>> c0854a4f45e67e3799fbe293e8de39f4e107ca74
